# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='avgFailureTime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='avgResolutionTime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='device',
            name='clientName',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='uptime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
