# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0002_auto_20160616_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alertID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='clientName',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='scrape.Device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='timeClosed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alert',
            name='timeOpened',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alert',
            name='deviceName',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
